### PR TITLE
Refactor/docs

### PR DESCRIPTION
**Pull request by pellebjerkestrand**
Adds scripts to generate missing doc files and generate the main readme.

### CODE REVIEW

**Comment by pellebjerkestrand** [comment]
`generate` only runs on Travis, though, where the documentation doesn't matter.

I added `generate:docs` to generate individual documentation files and build `README.md`.

**Comment by asbjornh** [comment]
Cool! Well I was thinking that since travis publishes to npm it would be nice if travis also generated the readme in case we forget to generate it manually (which will happen at some point). Should've mentioned this in the last comment. :)

I also thought about something else. When handling missing docs files we could make the script fail instead of adding an empty .md file. That way we could enforce documentation for all new utils (through failing travis build). I think that this would be slightly better than adding TODOs which might or might not be acted upon :)

**Comment by pellebjerkestrand** [comment]
I can make a test that looks for missing docs and/or missing parts in `README.md`.

**Comment by asbjornh** [comment]
Yeah that's probably a better idea than what I said :P

**Comment by asbjornh** [comment]
But then `generate-docs` shouldn't be run on travis I guess, as it would make the test pass

**Pull request merged**
